### ISSUE TITLE
Incorrect match results

### ISSUE THREAD

**Issue by ledaiduongvnth** [brunolinux/shape_matching#1]
@brunolinux 
After running provided example I couldn't get the detected object by cropping according to `x, y, angle` from `MatchResult `object. It seems the angle is correct but x, y are not correct, I see that after visualization. Please explain a little bit about the problem!

**Comment by brunolinux** [comment]
@ledaiduongvnth , you can try the code from the repo: https://github.com/meiqua/shape_based_matching
I have just refactored the code to better originazation.
